//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reca.TechnicalService.Finance.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string IBAN { get; set; }
        public string AdditionalInformation { get; set; }
        public int InvoiceId { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
