//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reca.TechnicalService.Rental.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> MaxPayDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int CustomerId { get; set; }
        public Nullable<bool> InvoiceState { get; set; }
        public string AdditionalInformation { get; set; }
        public int RentalId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Rental Rental { get; set; }
    }
}
