//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reca.TechnicalService.Vehicles.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string LicenseNumber { get; set; }
        public string VehicleType { get; set; }
        public Nullable<System.DateTime> VehicleYear { get; set; }
        public string VehicleColor { get; set; }
        public Nullable<int> MaxPersonsCount { get; set; }
        public string VehicleBrand { get; set; }
        public Nullable<decimal> VehicleCost { get; set; }
        public string VehicleInsurance { get; set; }
        public Nullable<bool> VehicleStatus { get; set; }
    }
}
